/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALEXIS
 */
public class VistaTelas extends javax.swing.JFrame {

    private GestionTelas gestorTelas;
    private DefaultTableModel modeloTabla;
    private Integer idTelaSeleccionada = null;
    private boolean cambiosPendientes = false;

    private static final java.util.logging.Logger 
            logger = java.util.logging.Logger.getLogger(VistaTelas.class.getName());

    /**
     * Creates new form VistaTelas
     */
    public VistaTelas() {
        initComponents();
        setLocationRelativeTo(null);

        configurarTabla();

        try {

            gestorTelas = new GestionTelas();
            actualizarTabla();

        } catch (IOException | IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this,
                    "No se pudieron cargar las telas: " + e.getMessage(),
                    "Error de carga", JOptionPane.ERROR_MESSAGE);

            btnRegistrar.setEnabled(false);
            btnBuscar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnGuardar.setEnabled(false);
        }

    }

    private void configurarTabla() {
        modeloTabla = (DefaultTableModel) tblTelas.getModel();
        modeloTabla.setRowCount(0);
    }

    private void actualizarTabla() {

        modeloTabla.setRowCount(0);

        for (Tela tela : gestorTelas.listar()) {

            modeloTabla.addRow(new Object[]{tela.getIdTela(), tela.getCodigo(),
                tela.getNombre(), tela.getDescripcion()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTelas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Telas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Gestión de tipos de telas:");

        jLabel2.setText("Codigo:");

        txtCodigo.addActionListener(this::txtCodigoActionPerformed);

        jLabel3.setText("Nombre:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        jLabel4.setText("Descripcion:");

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnBuscar.setText("Buscar por codigo");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnGuardar.setText("Guardar cambios");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        tblTelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Codigo", "Nombre", "Descripcion"
            }
        ));
        tblTelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTelas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnEliminar)
                                            .addGap(34, 34, 34)
                                            .addComponent(btnLimpiar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnRegistrar)
                                            .addGap(34, 34, 34)
                                            .addComponent(btnBuscar)))
                                    .addGap(14, 14, 14)))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnModificar)
                                .addComponent(btnGuardar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescripcion))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnBuscar)
                    .addComponent(btnModificar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGuardar))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        try {

            String codigo = txtCodigo.getText();
            String nombre = txtNombre.getText();
            String descripcion = txtDescripcion.getText();

            gestorTelas.registrar(codigo, nombre, descripcion);
            cambiosPendientes = true;
            actualizarTabla();
            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Tela registrada. "
                    + "Presiona Guardar cambios para conservarla.");

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Datos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        idTelaSeleccionada = null;
        tblTelas.clearSelection();

        txtNombre.setText("");
        txtDescripcion.setText("");

        try {

            String codigo = txtCodigo.getText();
            Tela tela = gestorTelas.buscarPorCodigo(codigo);

            if (tela == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró una tela con ese código.");
                return;
            }

            idTelaSeleccionada = tela.getIdTela();

            txtCodigo.setText(tela.getCodigo());
            txtNombre.setText(tela.getNombre());
            txtDescripcion.setText(tela.getDescripcion());

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Datos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if (idTelaSeleccionada == null) {
            JOptionPane.showMessageDialog(this,
                    "Primero busca la tela que deseas modificar.");
            return;
        }

        try {

            String codigo = txtCodigo.getText();
            String nombre = txtNombre.getText();
            String descripcion = txtDescripcion.getText();

            gestorTelas.modificar(idTelaSeleccionada, codigo, nombre, descripcion);
            cambiosPendientes = true;

            actualizarTabla();
            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Tela modificada en la sesión. "
                    + "Presiona Guardar cambios para conservar los cambios.");

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Datos inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {

            gestorTelas.guardarCambios();

            JOptionPane.showMessageDialog(this,
                    "Los cambios se guardaron correctamente.");

        } catch (IOException | IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this,
                    "No se pudieron guardar los cambios: " + e.getMessage(),
                    "Error de guardado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblTelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTelasMouseClicked

        int filaSeleccionada = tblTelas.getSelectedRow();

        if (filaSeleccionada == -1) {
            return;
        }

        int filaModelo = tblTelas.convertRowIndexToModel(filaSeleccionada);

        int idTela = Integer.parseInt(
                modeloTabla.getValueAt(filaModelo, 0).toString());

        Tela tela = gestorTelas.buscarTelaPorId(idTela);

        if (tela == null) {
            limpiarCampos();

            JOptionPane.showMessageDialog(this,
                    "La tela seleccionada ya no está disponible.");

            actualizarTabla();
            return;
        }

        idTelaSeleccionada = tela.getIdTela();

        txtCodigo.setText(tela.getCodigo());
        txtNombre.setText(tela.getNombre());
        txtDescripcion.setText(tela.getDescripcion());
    }//GEN-LAST:event_tblTelasMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (!cambiosPendientes) {
            dispose();
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Deseas guardar los cambios antes de salir?",
                "Guardar cambios", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {

            try {

                gestorTelas.guardarCambios();
                cambiosPendientes = false;
                dispose();

            } catch (IOException | IllegalArgumentException e) {

                JOptionPane.showMessageDialog(this,
                        "No se pudieron guardar los cambios: " + e.getMessage(),
                        "Error de guardado", JOptionPane.ERROR_MESSAGE);
            }

        } else if (respuesta == JOptionPane.NO_OPTION) {

            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (idTelaSeleccionada == null) {
            JOptionPane.showMessageDialog(this,
                    "Primero busca o selecciona la tela que deseas eliminar.");
            return;
        }

        Tela tela = gestorTelas.buscarTelaPorId(idTelaSeleccionada);

        if (tela == null) {
            JOptionPane.showMessageDialog(this,
                    "La tela seleccionada ya no existe.");

            actualizarTabla();
            limpiarCampos();
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Deseas eliminar la tela " + tela.getNombre() + "?",
                "Eliminar tela", JOptionPane.YES_NO_OPTION);

        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        try {

            gestorTelas.eliminar(idTelaSeleccionada);
            cambiosPendientes = true;

            actualizarTabla();
            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Tela eliminada de la sesión. "
                    + "Presiona Guardar cambios para conservar la eliminación.");

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Error al eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void limpiarCampos() {

        idTelaSeleccionada = null;

        txtCodigo.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");

        tblTelas.clearSelection();
        txtCodigo.requestFocusInWindow();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaTelas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTelas;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
