/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import clases.Produccion;
import clases.gestionProduccion;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALEXIS
 */
public class PanelProduccionDiaria extends javax.swing.JPanel {

    /**
     * Creates new form PanelProduccionDiaria
     */
    private gestionProduccion gestorProduccion;
    private DefaultTableModel modeloTabla;

    public PanelProduccionDiaria(gestionProduccion gestorProduccion) {

        if (gestorProduccion == null) {
            throw new IllegalArgumentException("Debes proporcionar la gestión de producción.");
        }

        initComponents();

        this.gestorProduccion = gestorProduccion;
        modeloTabla = (DefaultTableModel) tblProduccionDiaria.getModel();

        limpiarCampos();
    }

    private void consultarProduccion() {

        modeloTabla.setRowCount(0);
        lblTotal.setText("Total producido: —");

        try {
            String textoFecha = txtFecha.getText().trim();

            if (textoFecha.isEmpty()) {
                throw new IllegalArgumentException("Debes ingresar la fecha que deseas consultar.");
            }

            LocalDate fecha = LocalDate.parse(textoFecha);

            ArrayList<Produccion> resultados = gestorProduccion.buscarPorFecha(fecha);

            if (resultados.isEmpty()) {
                lblTotal.setText("Sin registros para la fecha consultada.");
                JOptionPane.showMessageDialog(this, "No hay registros de producción para esa fecha.");
                return;
            }

            for (Produccion produccion : resultados) {

                modeloTabla.addRow(new Object[]{
                    produccion.getIdProduccion(),
                    produccion.getHora().toString(),
                    produccion.getCantProducida(),
                    produccion.getTela().getNombre(),
                    produccion.getTurno().getNombre()
                });
            }

            int total = gestorProduccion.calcularTotalDiario(fecha);

            lblTotal.setText("Total producido el " + fecha + ": " + total + " unidades");

        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Ingresa una fecha válida en formato AAAA-MM-DD.", "Fecha incorrecta", JOptionPane.WARNING_MESSAGE);

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "No se pudo consultar", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void limpiarCampos() {

        txtFecha.setText("");
        modeloTabla.setRowCount(0);
        lblTotal.setText("Total producido: —");

        txtFecha.requestFocusInWindow();
    }

    public void actualizarPanel() {

        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btbConsultar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduccionDiaria = new javax.swing.JTable();

        jLabel1.setText("Fecha (AAAA-MM-DD)");

        btbConsultar.setText("Consultar");
        btbConsultar.addActionListener(this::btbConsultarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        lblTotal.setText("Total producido: —");

        tblProduccionDiaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hora", "Cantidad", "Tela", "Turno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduccionDiaria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btbConsultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbConsultar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbConsultarActionPerformed
        consultarProduccion();
    }//GEN-LAST:event_btbConsultarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbConsultar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblProduccionDiaria;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
